---
title: musemeta introduction
author: Scott Chamberlain
date: "2020-07-23"
output: rmarkdown::html_vignette
vignette: >
    %\VignetteIndexEntry{musemeta introduction}
    %\VignetteEngine{knitr::rmarkdown}
    %\VignetteEncoding{UTF-8}
---



Currently `musemeta` can get data from:

* [The Metropolitan Museum of Art](http://www.metmuseum.org/) via
    * scraping the MET website (see function `met()`)
    * http://scrapi.org (see functions `scrapi_()`)
* The [Canadian Science & Technology Museum Corporation](http://techno-science.ca/en/index.php) (CSTMC) (see functions `cstmc_()`)
* The [National Gallery of Art](http://www.nga.gov/content/ngaweb.html) (NGA) (see function `nga()`)
* The [Getty Museum](http://www.getty.edu/) (see function `getty()`)
* The [Art Institute of Chicago](http://www.artic.edu/) (see function `aic()`)

Other sources of museum metadata will be added...check back later & see [issues](https://github.com/ropensci/musemeta/issues).

## Install


```r
install.packages("musemeta")
```

OR


```r
remotes::install_github("ropensci/musemeta")
```


```r
library("musemeta")
```

## MET data

To get actual metadata for an object, you can use `met()` or `scrapi_get()` functions. The latter gets much more data, and uses a REST API, while the former scrapes the html directly, and can be more fragile with any changes in the html on the site.

### Scraping site directly

Data for a single object


```r
met(559490)
#> <Museum metadata> 559490
#>   title: NA
```

Or index to name of object, or values in the description


```r
met(559490)$name
#> [1] "559490"
```


```r
met(559490)$values[1:2]
#> [[1]]
#> [[1]]$name
#> [1] "title"
#> 
#> [[1]]$value
#> [1] NA
#> 
#> 
#> [[2]]
#> NULL
```

A different object


```r
met(246562)
#> <Museum metadata> 246562
#>   title: NA
```

Get many objects


```r
lapply(c(479283, 228901, 436876), met)
#> [[1]]
#> <Museum metadata> 479283
#>   title: NA
#> 
#> [[2]]
#> <Museum metadata> 228901
#>   title: NA
#> 
#> [[3]]
#> <Museum metadata> 436876
...
```

### Using the scrapi API

> Note: the `/random` endpoint is down.

This is again, for The Metropolitan Museum of Art only

Get a specific object


```r
scrapi_info(123, fields = c('title', 'primaryArtistNameOnly', 'medium'))
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: scrapi.org
```

Search for objects


```r
scrapi_search(query = 'mirror')
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: scrapi.org
```

Get an object, with a scrapi.org url


```r
out <- scrapi_get("http://scrapi.org/object/427581")
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: scrapi.org
out$primaryArtist
#> Error in eval(expr, envir, enclos): object 'out' not found
```

or an object id


```r
out <- scrapi_get(427581)
#> Error in curl::curl_fetch_memory(url, handle = handle): Could not resolve host: scrapi.org
out$primaryArtist
#> Error in eval(expr, envir, enclos): object 'out' not found
```

## CSTMC data

List changes


```r
cstmc_changes(limit = 1)
#> [[1]]
#> [[1]]$user_id
#> [1] "27778230-2e90-4818-9f00-bbf778c8fa09"
#> 
#> [[1]]$timestamp
#> [1] "2016-06-14T21:31:28.306231"
#> 
#> [[1]]$object_id
#> [1] "99f457c9-ea24-48a1-87be-b52385825b6a"
#> 
...
```

List datasets


```r
cstmc_datasets(as = "table")
#>  [1] "artifact-data-agriculture"                                  
#>  [2] "artifact-data-aviation"                                     
#>  [3] "artifact-data-bookbinding"                                  
#>  [4] "artifact-data-chemistry"                                    
#>  [5] "artifact-data-communications"                               
#>  [6] "artifact-data-computing-technology"                         
#>  [7] "artifact-data-domestic-technology"                          
#>  [8] "artifact-data-energy-electric"                              
#>  [9] "artifact-data-exploration-and-survey"                       
#> [10] "artifact-data-fisheries"                                    
...
```

Search for packages


```r
out <- cstmc_package_search(q = '*:*', rows = 2, as = 'table')
lapply(out$results$resources, function(x) x[,1:3])
#> [[1]]
#>                      resource_group_id cache_last_updated
#> 1 6869e3d9-5dfe-47bc-9ee7-e057ce0f13da                 NA
#> 2 6869e3d9-5dfe-47bc-9ee7-e057ce0f13da                 NA
#> 3 6869e3d9-5dfe-47bc-9ee7-e057ce0f13da                 NA
#> 4 6869e3d9-5dfe-47bc-9ee7-e057ce0f13da                 NA
#> 5 6869e3d9-5dfe-47bc-9ee7-e057ce0f13da                 NA
#> 6 6869e3d9-5dfe-47bc-9ee7-e057ce0f13da                 NA
#> 7 6869e3d9-5dfe-47bc-9ee7-e057ce0f13da                 NA
#>           revision_timestamp
#> 1 2016-06-14T19:59:16.022814
#> 2 2014-11-03T18:06:16.533032
#> 3 2014-11-05T18:39:52.229126
#> 4 2014-11-05T18:41:27.296672
#> 5 2016-06-14T20:00:42.660517
#> 6 2016-06-14T21:31:27.982837
#> 7 2016-06-14T21:30:26.277583
#> 
#> [[2]]
#>                      resource_group_id cache_last_updated
#> 1 aa9de49e-db0b-42f9-83dc-38464f6066ad                 NA
#> 2 aa9de49e-db0b-42f9-83dc-38464f6066ad                 NA
#> 3 aa9de49e-db0b-42f9-83dc-38464f6066ad                 NA
#> 4 aa9de49e-db0b-42f9-83dc-38464f6066ad                 NA
#> 5 aa9de49e-db0b-42f9-83dc-38464f6066ad                 NA
#>           revision_timestamp
#> 1 2016-06-14T18:53:55.201070
#> 2 2014-11-04T03:12:35.317249
#> 3 2014-11-05T21:53:33.722479
#> 4 2014-11-05T21:54:39.145752
#> 5 2016-06-14T18:59:17.785513
```

## National Gallery of Art (NGA)

Get metadata for a single object


```r
nga(id = 33267)
#> Error in xpathApply(tmp, "//div[@id='provenance']", xmlChildren)[[1]]: subscript out of bounds
```

Get metadata for many objects


```r
lapply(c(143679,27773,28487), nga)
#> Error in xpathApply(tmp, "//div[@id='provenance']", xmlChildren)[[1]]: subscript out of bounds
```

There is no search functionality yet for this source.

## Getty Museum

Get metadata for a single object


```r
getty(id = 140725)
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'doc' in selecting a method for function 'readHTMLTable': subscript out of bounds
```

Get metadata for many objects


```r
lapply(c(140725,8197), getty)
#> Error in h(simpleError(msg, call)): error in evaluating the argument 'doc' in selecting a method for function 'readHTMLTable': subscript out of bounds
```

There is no search functionality yet for this source.

## Art Institute of Chicago

Get metadata for a single object


```r
aic(41033)
#> <AIC metadata> 41033
#>    Artist:
#>       Name: NA
#>       Years: 
#>    Link: http://www.artic.edu/aic/collections/artwork/41033
#>    Title: NA
#>    Description: NA
#>    Description-2: NA
#>    Artwork body: 
#>    Exhibition history:
...
```

Get metadata for many objects


```r
lapply(c(41033,210804), aic)
#> [[1]]
#> <AIC metadata> 41033
#>    Artist:
#>       Name: NA
#>       Years: 
#>    Link: http://www.artic.edu/aic/collections/artwork/41033
#>    Title: NA
#>    Description: NA
#>    Description-2: NA
#>    Artwork body: 
...
```

There is no search functionality yet for this source.

## Asian Art Museum of San Francisco

Get metadata for a single object


```r
aam(11462)
#> <AAM metadata> Molded plaque (tsha tsha)
#>   Object Number: 1992.96
#>   Object name: Votive plaque
#>   Place of Origin: Western Tibet
#>   Historical Period: 
#>   Location: Gallery 12
#>   Culture: 
#>   Date: approx. 1992
#>   Artist: 
#>   Materials: Plaster mixed with resin and pigment
...
```

Get metadata for many objects


```r
lapply(c(17150,17140,17144), aam)
#> [[1]]
#> <AAM metadata> Boys sumo wrestling
#>   Object Number: 2005.100.35
#>   Object name: Woodblock print (nishiki-e)
#>   Place of Origin: 
#>   Historical Period: 
#>   Location: 
#>   Culture: 
#>   Date: approx. 1769
#>   Artist: Suzuki Harunobu (Japanese, 1725 - 1770)
...
```

There is no search functionality yet for this source.
